name: Build and Deploy React App

on:
  push:
    branches:
      - main  # Trigger workflow saat push ke branch main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Build project
      - name: Build
        run: pnpm run build

      # Deploy ke GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages          # branch tujuan deployment
          folder: build             # folder hasil build React
          token: ${{ secrets.GITHUB_TOKEN }}  # gunakan token rahasia GitHub
